### ISSUE TITLE
用spring boot 构建项目，使用web3sdk操作区块链。打成jar 包运行时，提示找不到ca.crt和client.keystore等资源文件

### ISSUE THREAD

**Issue by QQ-ing** [FISCO-BCOS/web3sdk#109]
1，我定义了一个初始化web3sdk的静态方法，在spring boot 启动后执行
`public class FiscoBcosSdk {
	private static Logger logger = LoggerFactory.getLogger(FiscoBcosSdk.class);
	private static ApplicationContext context=null;

	public static Web3j web3;
	public static Credentials credentials;
	
	public static void initObj() throws Exception {
		logger.info("(◉ω◉)===>Starting...");
		//初始化Service
		context = new ClassPathXmlApplicationContext("classpath:fisco-bcos/applicationContext.xml");
		Service service = context.getBean(Service.class);
		service.run();

		logger.info("(◉ω◉)===>初始化AOMP的ChannelEthereumService");

		ChannelEthereumService channelEthereumService = new ChannelEthereumService();
		channelEthereumService.setChannelService(service);
		
		//使用AMOP消息信道初始化web3j
		web3 = Web3j.build(channelEthereumService);
		
		EthBlockNumber ethBlockNumber = web3.ethBlockNumber().sendAsync().get();
		logger.info("(◉ω◉)===>获取ethBlockNumber:{}",ethBlockNumber.getBlockNumber());
		
		//初始化交易签名私钥
		ECKeyPair keyPair = Keys.createEcKeyPair();
		credentials = Credentials.create(keyPair);
		logger.info("(◉ω◉)===>blockchain sdk init success!");
	}}

`
public static void main(String[] args) {
	SpringApplication.run(DemoApplication.class, args);
	try {
		FiscoBcosSdk.initObj();
	} catch (Exception e) {
		logger.error("(T＿T)===>FiscoBcosSdk.initObj() throws exception!");
		e.printStackTrace();
	}

}
`

代码在我本地的idea上执行没有任何问题。如下图：
![image](https://user-images.githubusercontent.com/9510705/48612214-4593aa80-e9c3-11e8-9eb8-95d3b989a64c.png)

2，我吧项目用maven 导出成jar 包在mac电脑上(linux)执行，提示找不到ca.crt等资源文件。如下图：
![image](https://user-images.githubusercontent.com/9510705/48612289-8c81a000-e9c3-11e8-9114-da2226f3ded2.png)

**Comment by QQ-ing** [comment]
这个问题有可能是打成jar包后，他的资源地址前面带了个“jar:file...”。这样就找不到，我有搜相关Spring boot 读取resource资源相关的问题，但是大部分的解决方案是自己使用流来读取资源文件。不过web3sdk的接口是需要传递文件路径。这就很尴尬了。。。
另外我有试过获取ca.crt的文件绝对地址，然后传递过去依然是不行的 :-(

**Comment by yanyanho** [comment]
建议先看下https://fisco-bcos-documentation.readthedocs.io/zh_CN/v1.0.1/docs/web3sdk/config_web3sdk.html 这个使用文档，检查你的ca.crt是否放在resource目录下。

**Comment by QQ-ing** [comment]
@yanyanho 如下图是我的资源文件配置和文件位置。如果ca.crt 不在resource目录的话，应该在本地就跑不起来吧。。。
![image](https://user-images.githubusercontent.com/9510705/48620407-083b1700-e9db-11e8-961f-d433d8ef75a8.png)

**Comment by yanyanho** [comment]
看起来是在resource/fisco-bcos目录下,调整一下。

**Comment by QQ-ing** [comment]
@yanyanho 我有测试过吧ca.crt等文件移动到resource目录下，但是依然是这个结果的。。。

**Comment by yanyanho** [comment]
application.xml中的文件路径也相应改过来了吗？

**Comment by QQ-ing** [comment]
@yanyanho 是的呢

**Comment by yanyanho** [comment]
我这有个spring boot的demo。可以参考下https://github.com/yanyanho/web3jsdk-spring-boot-starter。可以看看。

**Comment by QQ-ing** [comment]
@yanyanho 好的，谢谢。我去看看！

**Comment by QQ-ing** [comment]
[SpringBoot加载外部依赖](url:https://www.jianshu.com/p/a2cf2336a48c
)
我将resources中所有资源拷贝了一份到jar包同级的目录下。使用
`java -Dloader.path=./resources -jar demo-0.0.1-SNAPSHOT.jar`
这个命令解决了此问题！

**Comment by yanyanho** [comment]
> 我参考了此文档 https://www.jianshu.com/p/a2cf2336a48c
> 我将resources中所有资源拷贝了一份到jar包同级的目录下。使用
> `java -Dloader.path=./resources -jar demo-0.0.1-SNAPSHOT.jar`
> 这个命令解决了此问题！
> 
> ![image](https://user-images.githubusercontent.com/9510705/48698915-40cd3180-ec23-11e8-8823-83113776d5e5.png)

优秀。
