### ISSUE TITLE
sh compile.sh 出现error  :Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by JordanPanther** [FISCO-BCOS/web3sdk#51]
執行sh compile.sh 後，出現錯誤：compile.sh: 7: compile.sh: Syntax error: "(" unexpected

**Comment by fisco-dev** [comment]
文件格式问题，用dos2unix转换一下
dos2unix compile.sh

**Comment by JordanPanther** [comment]
執行了 dos2unix compile.sh  仍然出現相同的問題
compile.sh: 7: compile.sh: Syntax error: "(" unexpected

**Comment by JordanPanther** [comment]
好了，已經解決啦，執行如下語句：
sudo dpkg-reconfigure dash
弹出窗口选择
No或者否
好象是因爲腳本中會將命令執行dash而不是bash，因此我們關閉dash的配置即可。
