### ISSUE TITLE
控制台报错Input byte array must be in range 0 < M <= 32 and length must match type

### ISSUE THREAD

**Issue by lilianwen** [FISCO-BCOS/web3sdk#689]
我的智能合约函数声明是
function Store(bytes memory payload, bytes32 hash, bytes memory signature) public 
在传入第二个参数的时候一直报错：
Input byte array must be in range 0 < M <= 32 and length must match type

我尝试不同的第二个参数长度，终于找到一个bug级别的错误，我传入的参数长度如下：
call TicketStorage 0x0b5b720823e3740f1d19fda77131343b050f3960 Store "0xdeadbeef" "0x000000000000000000000000000000" "0x00"
注意第二个参数实际上只有15个字节长度，但是这里却认为这是正确的bytes32，我暂时不知道这是控制台的bug还是web3sdk的bug，就在这里提了，因为找到报错的地方是在web3sdk。

**Comment by ywy2090** [comment]
控制台1.2.0之后的版本解决了这个问题。

**Comment by zhangjiyh** [comment]
似乎并没有被解决
